[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "localmath_Aditya"  # IMPORTANT: Read the note below!
version = "0.1.0"
authors = [
    { name="Aditya", email="adityasrichandan275@gmail.com" },
]
description = "A local mathematics operations tool with an interactive menu."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com"
